base_url = "https://medianrarity.github.io/"
title = "meanrare"
description = "Personal site"
default_language = "en"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = false

[extra]
